travis:
  secure:
    BINSTAR_TOKEN: GAf1XMZg8vtuNdWAtu2JEDqZ425fUdN0pyyYL1MrV/mfNzMb7KLYs9aD79nyMZfzaYkCd+Lpx2lhGpsgTpPspy6meG6o8Xr9DB0+Z9yoE6u4A2DqaDryN7x9kd/4TdOYYTX8YxLSNvYk78SCYLr2PjqIy0LsGels6vt7Q6vzK/OGrE3CVSNEm9jOVGmsiSSemdg04Ly4Xf1CKjIEvjWcnZ+6lq9G+ekywXtV3q5/Akyxqrv2Es5UBV2VsJPvc6wfXKueiVE16i/LU2bxi+OU3slvLvtIhOPZUkwqCZHJT4WgRrmQH0Y4TTtw9lbRG1AnHw6SKmuHa3RZumHhrVDPFeSnbNj4o7/MpZ/9cb3CsTaEajCtpsWdnkzqG2XB6H4aH7xY0hwsB1Rh4U/geHBjmg5wbgoixRISrQfTFW+QWxonVOBrLfyxq7PAvTo47nfMD1w80E/q6HH3xdAr8xrws+nmWMfWfPYidYcCEz8kKPksILBf1ZWYMKEVat5RHnp1Mq+9OUmKcrkn+zsykgkEqn0UWeD48dO6T1CuqVl1nX5+pl8VyRBIC4xrtE2dcBI9Ugduu+6OL6/Ae+873IJokLFgqmF0+KOkwbZs7dtooOzXUbGH3adNTO35UwuuxSH3z1nCg7RoYGrsdMdvwzhBkWKqVqmhGHuJTjsdHfoVcd8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
